---
# This Task configure namenode

- name: Configure etc/hadoop/hdfs-site.yml file
  template: src=templates/hdfs-site.xml dest=/usr/local/{{ hadoopDir }}/etc/hadoop/hdfs-site.xml backup=yes
  become: yes
  become_user: "{{ specialUser }}"

- name: Append datanode hostnames to workers file
  lineinfile: path=/usr/local/{{ hadoopDir }}/etc/hadoop/hdfs-workers 
    line={{ hostvars[item]['hostName'] }} create=yes
  with_items: "{{ groups[dataNodeGroupName] }}"
  become: yes
  become_user: "{{ specialUser }}"

- name: Empty default workers file
  copy: content='' dest=/usr/local/{{ hadoopDir }}/etc/hadoop/workers
  become: yes
  become_user: "{{ specialUser }}"

- name: Append datanode hostnames to default workers file
  lineinfile: path=/usr/local/{{ hadoopDir }}/etc/hadoop/workers 
    line={{ hostvars[item]['hostName'] }} create=yes
  with_items: "{{ groups[dataNodeGroupName] }}"
  become: yes
  become_user: "{{ specialUser }}"

- name: Create HDFS data dir
  file: path={{ nameNodeDataDir }} state=directory 
    owner={{ specialUser }} group={{ specialUser }}
  become: yes
